### ISSUE TITLE
Dockerfile ignores local changes

### ISSUE THREAD

**Issue by Laurian** [nypublicradio/audiogram#44]
This prescription will ignore local changes (really confusing):

```
git clone https://github.com/nypublicradio/audiogram.git
cd audiogram
docker build -t audiogram .
```

As `Dockerfile` specifies `RUN git clone https://github.com/nypublicradio/audiogram.git`.

A quick fix I made for @evoterra: https://gist.github.com/Laurian/32a1250e270ad5d31a75e0a729179c79

**Comment by Laurian** [comment]
Note that in that quickfix I commented out `USER audiogram` due to some permission errors: 
```
audiogram@0.9.4 postinstall /home/audiogram/audiogram
mkdir -p editor/js && browserify client/index.js > editor/js/bundle.js

mkdir: cannot create directory 'editor/js': Permission denied
```

**Comment by veltman** [comment]
That permissions issue is part of the reason why it clones from the repo rather than copying locally, because Docker unfortunately doesn't allow `ADD` as anything other than root:

https://github.com/docker/docker/issues/6119

But the more general issue is that changes being reflected in Docker will depend on where you make them in either case.  For example, `ADD`ing the files will incorporate initial changes but not subsequent ones.

Among other options, you can:

1. Edit the `themes.json` file in the Docker container.
2. Edit the `themes.json` file locally and copy it.
3. Mount the `settings` folder in the container.

https://github.com/nypublicradio/audiogram/issues/39#issuecomment-239681199

I'm not sure there is any ideal solution to these tradeoffs, but resolving #32 should make it mostly irrelevant by eliminating the need to customize by directly editing source files.

**Comment by frenchpress** [comment]
Laurian,
I think this thread is relevant to my issue, but it's a bit over my head.

I've made some simple changes to themes.json. Different name, color and background image. Image is in the correct folder. Committed in GitHub and synced. This new theme is not showing up in the dropdown menu. Thoughts?

**Comment by Laurian** [comment]
See #50 as a solution, or modify the Dockerfile in your fork to git clone from your repo.

**Comment by frenchpress** [comment]
Thank you, Laurian. I've put in an additional query on #50. I don't know how to modify the Dockerfile—or what a "fork" is. I'm sorry. I've never attempted anything like this before.
