### ISSUE TITLE
Audio quality degrades after running through Audiogram

### ISSUE THREAD

**Issue by vanityclear** [nypublicradio/audiogram#51]
The quality of the audio has gotten distinctly tinny and somewhat echo-y after it's put through Audiogram—this is with a 1:09 minute long mp3. Is this a known issue?

**Comment by veltman** [comment]
We haven't had any issues with this, and we've tested a number of formats and bitrates, but it could depend on the specific encoding of the file you're using. Can you run `ffprobe` or something similar and paste the output here?

If you want to pick your own audio encoding options, you can edit:

https://github.com/nypublicradio/audiogram/blob/master/audiogram/combine-frames.js#L7

**Comment by vanityclear** [comment]
I'm a little new to this, can you tell me what to run with ffprobe? Should I run 

$ ffprobe -encode 

Or something else? I tried running:

$ ffprobe -show_format [file location]

after running Docker/audiogram (so in the Docker container), but the file I want is in my Downloads folder, since that's where Audiogram saves it. I tried putting in the path name to the file in there, but it kept giving me the error message "No such file or directory"

Thank you!

**Comment by vanityclear** [comment]
Thanks, Noah. When I run ffprobe [mp3 filename] it seems to freeze up and do nothing. So here are the files...

mp3: https://www.dropbox.com/s/6fu7i6u44oqdemh/SP160926_fallpromo_v4.mp3?dl=0
wav: https://www.dropbox.com/s/g1kgsgdkzzuwxvr/SP160926_fallpromo_v4.wav?dl=0
mp4: https://www.dropbox.com/s/88sxqwbp6usmj63/Smarty%20Pants%20Theme%20-%202016-10-07%20at%2012.09pm.mp4?dl=0

**Comment by veltman** [comment]
Hmm, I'm not able to reproduce this - the quality doesn't degrade substantially.

If `ffprobe` is failing there might be some issue with your `ffmpeg` installation so I'd try reinstalling it. I also notice that the mp3 is an odd bitrate (126 kbps instead of 128).

It does ultimately get encoded as 128 kbps in the video per Facebook/Twitter specs, so it's possible that introduces some artifacts depending on your specific codecs. Do you still experience the same problem if you use the `.wav` file or reencode it as a 128 kbps mp3?
